name: docker-workflow
on:
    push:
jobs:
    docker-login:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
              
            - name: Login step
              run: |
                echo "Docker login step"
                ls -a
                cat Dockerfile
              