name: Environment workflow
on:
 push:
jobs:
    Development_job:
      runs-on: ubuntu-latest
      env:
        PROJECT: "Development project"
      steps:
       - name: First_step
         run: echo "This is ${{ env.PROJECT }}"
    
    Production_job:
      uses: ./.github/workflows/reusable-workflow.yml
      with:
        PROJECT: "Production project."
