name: Environment workflow
on:
 push:
jobs:
  Development_job:
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      PROJECT: "Development and QA project.."
      VERSION: 1
    secrets:
      AWS_REGION: ${{ secrets.AWS_REGION }}
    
  Production_job:
    uses: ./.github/workflows/reusable-workflow.yml
    secrets: 
      AWS_REGION: ${{ secrets.AWS_REGION }}
    with:
      PROJECT: "Production project."
      
