name: Environment workflow
on:
 push:
jobs:
  Development_job:
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      PROJECT: "Development and QA project.."
      VERSION: 1
    
  Production_job:
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      PROJECT: "Production project."
      
