name: Reusable Workflow
on:
    workflow_call:
      inputs:
        PROJECT:
            required: true
            type: string
        VERSION:
          required: false
          type: number
jobs:
    intro_step:
        runs-on: ubuntu-latest
        steps:
          - name: First_step
            run: echo "This is ${{ inputs.PROJECT }} of version - ${{ inputs.VERSION }}"
    